version: "3.9"
services:
  sanednf:
    build: .
    restart: always
    ports:
      - "3000:3000"
    networks: 
      - network-proxy
      - back
networks:
  network-proxy:
    external:
      name: network-proxy
  back:
    driver: bridge
  host:
    driver: host
